name: Deploy Backend
permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      tier:
        description: "Environment to deploy to"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - qa

jobs:
  deploy-backend:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    environment: ${{ inputs.tier }}
    env:
      TIER: ${{ inputs.tier || 'dev' }}
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      SSL_CERTIFICATE_ARN: ${{ secrets.SSL_CERTIFICATE_ARN }}

    steps:
      - uses: actions/checkout@v4

      - name: Install CDK
        run: npm install -g aws-cdk

      - name: Install CDK dependencies
        run: |
          cd infrastructure
          npm ci

      - name: Deploy Lambda + API Gateway
        run: |
          cd infrastructure
          npx cdk deploy \
            LambdaGetAnnotations-${{ env.TIER }} \
            LambdaWriteAnnotations-${{ env.TIER }} \
            LambdaGetFamily-${{ env.TIER }} \
            LambdaListFamilies-${{ env.TIER }} \
            LambdaListStudies-${{ env.TIER }} \
            LambdaJsonProcessor-${{ env.TIER }} \
            ApiGateway-${{ env.TIER }} \
            --require-approval never
